env_name: "gym_examples/contGrid-v5"
state_dim: 3
action_dim: 1
action_range: [0, 6.28318]
F: 1
vel_field: "/home/rohit/Documents/Research/Planning_with_transformers/Translation_transformer/my-translat-transformer/data/GPT_dset_DG3/static_obs/GPTdset_DG3_g100x100x120_r5k_Obsv1_w5_1"
del_t: 1.
scale_velocity: False
vmax_by_F: 1
space_scale: 1
target_radius: 2

add_transition_noise_during_inf: False
noise_var: [0.1,0]

dataset_name: "GPTdset_DG3"
dataset_path: "data/GPT_dset_DG3/static_obs/GPTdset_DG3_g100x100x120_r5k_Obsv1_w5_1dataset_v1.pkl"
log_dir: "log"
params2_name: "data/DG3/params.yml"

random_split: True
split_tr_tst_val: [0.8, 0.1, 0.1]
split_ran_seed: 42
comp_val_loss: False
translate_earlybreaks: [100, 200, 250]

max_eval_ep_len: 120
num_eval_ep: 200
eval_inerval: 3
batch_size: 64

lr: 0.000005
use_scheduler: True
wt_decay: 0.0001
warmup_steps: 500
num_epochs: 6
num_updates_per_iter: 500
add_target_loss: False
a_tl: 1000

target_conditioning: True 
num_encoder_layers: 4
num_decoder_layers: 4
context_len: 120
embed_dim: 32
n_heads: 32
dropout_p: 0.1

device: 'cuda'
