env_name: "gym_examples/contGrid-v5"
state_dim: 3
action_dim: 1
action_range: [0, 6.28318]
F: 1
vel_field: "/home/sumanth/rohit/Translation_transformer/my-translat-transformer/data/DOLS_Cylinder/targ_5"
del_t: 1.
scale_velocity: True
vmax_by_F: 1
space_scale: 15
target_radius: 2

add_transition_noise_during_inf: False
noise_var: [0.1,0]

dataset_name: "DOLS_Cylinder"
dataset_path: "/home/sumanth/rohit/Translation_transformer/my-translat-transformer/data/DOLS_Cylinder/targ_5/gathered_targ_5.pkl"
              
log_dir: "log"
params2_name: "data/DOLS_Cylinder/params.yml"

random_split: True
split_tr_tst_val: [0.8, 0.05, 0.15]
# split_tr_tst_val: [0.01, 0.98, 0.01]

split_ran_seed: 42
comp_val_loss: False
translate_earlybreaks: [50, 200, 500]

max_eval_ep_len: 101 # redundant
num_eval_ep: 200
eval_inerval: 5
batch_size: 32

optimizer_name: 'AdamW'
lr: 0.001
final_lr: 0.000001
use_scheduler: True
wt_decay: 0.001
warmup_steps: 10000 #redundant
num_epochs: 200
num_updates_per_iter: 500 #redundant
add_target_loss: False
a_tl: 1000

target_conditioning: False 
num_encoder_layers: 4
num_decoder_layers: 4
context_len: 101
embed_dim: 32
n_heads: 8
dropout_p: 0.1

# mlp_bc
hidden_size: 512
n_layers: 10

device: 'cuda'
